import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { DropdownMenuContent } from "@radix-ui/react-dropdown-menu";
import { Edit2, MoreVertical, MoveLeft, Plus, User2 } from "lucide-react";
import React from "react";
import Wrapper from "../_wrapper";
import Head from "next/head";
import { Metadata } from "next";
import a from "@/components/a";

export const metadata: Metadata = {
  title: "User skills",
  description: "Generated by create next app",
};

function Page() {
  return (
    <Wrapper>
      <Head key={"red"}>
        <title>Hello world</title>
      </Head>
      <Card className="">
        <CardHeader className="flex flex-row justify-between items-center gap-5">
          <div className="flex items-center md:gap-6 gap-4">
            <a href="/" back={true}>
              <MoveLeft className="w-5 h-5 opacity-80 hover:opacity-100" />
            </a>
            <CardTitle className="font-semibold text-lg">Skills</CardTitle>
          </div>

          <Plus className="w-5 h-5 opacity-80 hover:opacity-100" />
        </CardHeader>
        <CardContent>
          <div className="flex py-3 gap-1 justify-between items-center">
            <h3 className="font-semibold text-base">Skilled muti-taker</h3>
            <DropdownMenu>
              <DropdownMenuTrigger className="focus-visible:outline-none">
                <MoreVertical className="h-5 w-5" />
              </DropdownMenuTrigger>
              <DropdownMenuContent className="mt-2 p-2 bg-background rounded-lg shadow-lg">
                <DropdownMenuGroup>
                  <DropdownMenuItem>
                    <Edit2 className="w-1.5 h-1.5" />
                    <span className="text-sm">Edit</span>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <Edit2 className="w-1.5 h-1.5" />
                    <span className="text-sm">Delete</span>
                  </DropdownMenuItem>
                </DropdownMenuGroup>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
          <hr />
          <div className="flex flex-col pb-1 pt-4 gap-1">
            <h3 className="font-semibold text-base">
              Full Stack web Developer
            </h3>
          </div>
          <hr />
        </CardContent>
      </Card>
    </Wrapper>
  );
}

export default Page;
