"use client";

import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Generated by Copilot
interface LocationState {
  currentLocation: string | null;
  previousLocation: string | null;
  history: string[];
}

const initialState: LocationState = {
  currentLocation: null,
  previousLocation: null,
  history: [],
};

const locationSlice = createSlice({
  name: "location",
  initialState,
  reducers: {
    navigate: (state, action: PayloadAction<string>) => {
      state.previousLocation = state.currentLocation;
      state.currentLocation = action.payload;
      state.history.push(action.payload);
    },
    goBack: (state) => {
      if (state.previousLocation) {
        const currentLoc = state.currentLocation;
        state.currentLocation = state.previousLocation;
        state.previousLocation = currentLoc;
        state.history.push(state.currentLocation);
      }
    },
    clearHistory: (state) => {
      if (state.currentLocation) state.history = [state.currentLocation];
    },
  },
});

export const { navigate, goBack, clearHistory } = locationSlice.actions;
export default locationSlice.reducer;
